### PR TITLE
Use rust-bitcoin for script handling

### PR DESCRIPTION
**Pull request by gcarq**

### CODE REVIEW

**Comment by gcarq** [comment]
SimpleStats output from this branch

```
SimpleStats:
   -> valid blocks:             639626
   -> total transactions:       549390991
   -> total tx inputs:          1347165535
   -> total tx outputs:         1458038650
   -> total tx fees:            209622.12479701 (20962212479701 units)
   -> total volume:             5621855102.66414261 (562185510266414236 units)

   -> biggest value tx:         550000.00000000 (55000000000000 units)
        seen in block #153509, txid: 29a3efd3ef04f9153d47a990bd7b048a4b2d213daaa5fb8ed670fb85f13bdbcf

   -> biggest size tx:          999657 bytes
        seen in block #364292, txid: bb41a757f405890fb0f5856228e23b715702d714d59bf2b1feb70d8b2b4e3e08

Averages:
   -> avg block size:           0.94 KiB
   -> avg time between blocks:  9.57 (minutes)
   -> avg txs per block:        858.93
   -> avg inputs per tx:        2.45
   -> avg outputs per tx:       2.65
   -> avg value per output:     3.86

Transaction Types:
   -> Pay2PublicKey: 3256132 (0.22%)
        first seen in block #0, txid: 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b

   -> Pay2WitnessScriptHash: 3540113 (0.24%)
        first seen in block #481824, txid: 461e8a4aa0a0e75c06602c505bd7aa06e7116ba5cd98fd6e046e8cbeb00379d6

   -> Pay2ScriptHash: 331759432 (22.75%)
        first seen in block #170052, txid: 9c08a4d78931342b37fd5f72900fb9983087e6f46c4a097d8a1f52c74e28eaf6

   -> Unspendable: 1 (0.00%)
        first seen in block #251527, txid: 8a68c461a2473653fe0add786f0ca6ebb99b257286166dfb00707be24716af3a

   -> NotRecognised: 920189 (0.06%)
        first seen in block #71036, txid: e411dbebd2f7d64dafeef9b14b5c59ec60c36779d43f850e5e347abee1e1a455

   -> Pay2WitnessPublicKeyHash: 48873728 (3.35%)
        first seen in block #481824, txid: dfcec48bb8491856c353306ab5febeb7e99e4d783eedf3de98f3ee0812b92bad

   -> WitnessProgram: 15 (0.00%)
        first seen in block #608548, txid: b53e3bc5edbb41b34a963ecf67eb045266cf841cab73a780940ce6845377f141

   -> OpReturn(""): 45255301 (3.10%)
        first seen in block #228596, txid: eb31ca1a4cbd97c2770983164d7560d2d03276ae1aee26f12d7c2c6424252f29

   -> Pay2PublicKeyHash: 1024433739 (70.26%)
        first seen in block #728, txid: 6f7cf9580f1c2dfb3c4d5d043cdbb128c640e3f20161245aa7372e9666168516


[15:28:50] INFO - main: Fin.
        Command being timed: "cargo run --release -- -v -d /path/to/blocks simplestats"
        User time (seconds): 21330.37
        System time (seconds): 7254.49
        Percent of CPU this job got: 380%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:05:19
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 114208
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 9
        Minor (reclaiming a frame) page faults: 38428
        Voluntary context switches: 30586530
        Involuntary context switches: 48217153
        Swaps: 0
        File system inputs: 543061904
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by dev4an3** [comment]
Please can you tell me when the SegWit support is ready to merge. Or maybe you have some documentation how I can use the updated files. I work only with the Bitcoin blockchain on a windows system.

**Comment by gcarq** [comment]
This PR is ready, but I will not merge it yet as it breaks all coins that have a magic value other than bitcoin.

**Comment by gcarq** [comment]
This PR is no longer relevant as all the necessary changes are finalized an pushed on master

**Pull request closed without merging**
