### PR TITLE
Add unspent balance output

### PR DESCRIPTION
**Pull request by fsvm88**
Hi!
Would you be interested in merging these patches?
They add unspent CSV output dump as a CSV file (balance for all addresses where balance != 0).
Consider that it was my first attempt at writing code in rust and was mostly taken and modelled on the csvdump callback.
It uses a hashmap and preallocates around 10mln entries, which sort of reflects the number of unique unspent addresses at the time I wrote it (August last year).
The module can be useful to avoid having 150GB+ SQL databases just for tracking unspent output.
There's no suspend/resume support (would need to serialize/unserialize the hashmap to disk I guess).

### CODE REVIEW

**Comment by Napulsnik** [comment]
Hello. What is command for get all unspend balances?

**Comment by fsvm88** [comment]
Hi @Napulsnik, the command is "unspentcsvdump".
You should use it just like csvdump, it doesn't currently support/make use of the resume option, so it will always run on the entire blockchain.

**Comment by Napulsnik** [comment]
Thank you!

**Comment by Napulsnik** [comment]
Need a lot of memory. If you send me fresh list of all bitcoin addresses with balance I pay you 10$ in bitcoin. Deal?

**Comment by fsvm88** [comment]
@Napulsnik Yup, it does need a lot of memory. Thanks for the offer, but I'd need to download and sync the entire blockchain and then run the whole thing. Don't have that much spare time atm. :)

**Comment by Napulsnik** [comment]
Ok.

**Comment by gcarq** [comment]
I will update the README to reflect that change.

**Comment by edenweb1** [comment]
@Napulsnik , I have a fresh csv list if you are interested !

**Comment by Napulsnik** [comment]
No longer needed

**Pull request merged**
